library/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.mains,name= "mains"),
    path("mains/", views.mains,name= "mains"),
    path("addbook/",views.add_book,name="addbook"),
    path("<pk>/delbook", views.delete_book,name="delbook"),
    path('<pk>/singlebook', views.single_book, name="single_book"),
    path('<pk>/edit', views.edit_book, name="edit"),
    path('searchbooks', views.search_books, name="searchbooks"),
    path("authors/", views.authors,name= "authors"),
    path("addauthor/",views.add_author,name="add_author"),
    path("<pk>/delauthor", views.delete_author,name="delete_author"),
    path('<pk>/singleauthor', views.single_author, name="single_author"),
    path('<pk>/editauthor', views.edit_author, name="edit_author"),
    path('searchbooks', views.search_books, name="searchbooks")
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include('books.urls')),
    path("loans/", include('loans.urls')),
    path("users/", include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/loans/urls.py
from django.urls import path
from . import views

app_name = "loans"

urlpatterns = [ 
    path('<pk>/loan',views.loans,name= 'loan'),
    path('loans/',views.loan_list_private,name= 'loans'),
    path('adminloans/',views.loan_list,name= 'adminloans'),
    path('lateloans/',views.late_loans,name= 'lateloans'),
    path('<pk>/latecheck',views.late_check,name= 'latecheck'),
    path('<pk>/return',views.returns,name= 'return')
]

library/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_func, name="login_func"),
    path('loginout/', views.logout_func, name="logout_func"),
    path("register", views.register_request, name="register"),
    path('user/', views.user_menu, name="user"),
    path('showuser/', views.single_user, name="showuser"),
    path('firstlogin/', views.first_login, name="firstlogin"),
    path('customerlist/', views.customer_list, name="customerlist"),
    path('<pk>/deluser', views.deluser, name="deluser"),


]

library/books/models.py
from enum import Enum
from django.db import models 
from django.contrib.auth.models import User
import datetime

class Authors(models.Model):
   name = models.CharField(max_length=40, unique=True)
   age = models.IntegerField()
   nationality = models.CharField(max_length=40 )

   def __str__(self):
      return f"{self.name}"+ f"{self.age}"


class BookType(Enum):
   ten_days = 1
   five_days = 2
   two_days = 3

class LoanStatus(Enum):
   available = 1
   loaned = 2


class Book(models.Model):

   class BookType2(models.IntegerChoices):
      ten_days = 10, "Ten Days Loan"
      five_days = 5, "Five Days Loan"
      two_days = 2, "Two Days Loan"
   
   class LoanStatus2(models.TextChoices):
      LOANED = 'L', 'Loaned'
      AVAILABLE = 'A', 'Available'


   name = models.CharField(max_length=40, null=False)
   author = models.ForeignKey(Authors,on_delete=models.CASCADE)
   YEAR_CHOICES = []
   for r in range(1900, (datetime.datetime.now().year+1)):
      YEAR_CHOICES.append((r,r))
   year_published = models.IntegerField(('year'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)
   type = models.SmallIntegerField(null=False, default = BookType.two_days, choices=BookType2.choices)
   image = models.ImageField(null=False, blank=False, default='placeholder.png')
   status =models.CharField(max_length=40, null=False, default= LoanStatus2.AVAILABLE, choices= LoanStatus2.choices)
   
   def get_rating(self):
         total = sum(int(review['stars']) for review in self.reviews.values())
         if total == 0:
            return total
         else:
            return total / self.reviews.count()
   
   def __str__(self):
    return f"{self.name} {self.author.name}"

class BookReview(models.Model):
      book = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE)
      customer = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
      content = models.TextField(blank=True, null=True)
      stars = models.IntegerField()
      date_added = models.DateTimeField(auto_now_add=True)  

      

library/loans/models.py
from enum import Enum
from django.db import models
from django.contrib.auth.models import User
from books.models import Book

# Create your models here.


class LoanStatus(Enum):
   available = 1
   loaned = 2


class Loan(models.Model):
    class LoanTime(models.TextChoices):
       OVERTIME = 'O', 'Late Return'
       ONTIME = 'V' , 'Good'

    custID = models.ForeignKey(User, on_delete=models.CASCADE)
    bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
    loandate = models.DateField(auto_now_add=True)
    returndate = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=40, null=False, default= LoanTime.ONTIME, choices=LoanTime.choices)

    def __str__(self):
      return f'{self.custID} - {self.returndate}'

library/books/forms.py
from django.forms import ModelForm
from books.models import Book,Authors

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'year_published', 'type', 'image'] 


class AuthorForm(ModelForm):
    class Meta:
        model = Authors
        fields = ['name','age', 'nationality'] 

library/books/views.py
from django.shortcuts import render,redirect
from books.forms import BookForm, AuthorForm
from books.models import Book, Authors,BookReview
from loans.views import late_check
from loans.models import Loan
from django.contrib import messages
from django.db.models import Q
from django.contrib.admin.views.decorators import staff_member_required
from books.models import BookReview
from loans.models import Loan
from loans.views import late_check


def mains(request):
   mybooks = Book.objects.all()
   context = {
       'book_list': mybooks,
   }
   return render(request,'mains.html',context=context)

@staff_member_required
def add_book(request):
    if request.method == "POST":
        bookform = BookForm(request.POST, request.FILES)
        if bookform.is_valid():
            bookform.save()
            return redirect('books:mains')          
    else:
        bookform = BookForm()
   
    context = {
        'bookform': bookform,
    }
    return render(request, "add_book.html", context=context)
        
def search_books(request):
    search = request.GET.get('search')
    books = Book.objects.filter(Q(name__contains= search))
    context = {
        'book_list' : books,
    }
    return render(request, 'mains.html', context= context)

@staff_member_required
def delete_book(request,pk):
    book = Book.objects.get(id=pk)
    book.delete()
    return redirect('books:mains')

## Reviews:

def single_book(request, pk):
    book = Book.objects.get(id=pk)
    try:
        loan = Loan.objects.get(bookID=pk)
        late_check(loan.id)
    except:
        pass
    if request.method == 'POST' and request.user.is_authenticated:
        stars = request.POST.get('stars', 3)
        content = request.POST.get('content', '')

        review = BookReview.objects.create(book=book, customer=request.user, stars=stars, content=content)

        return redirect('books:mains')
    try:
        reviews = show_reviews(pk)
        context = {
        'reviews' : reviews,
        'book' : book,
    }
    except:
        context = {
        'book' : book,
        }
    return render(request,'single_book.html',context = context)

def show_reviews(pk):
    current_book = Book.objects.get(id=pk)
    reviews = BookReview.objects.all().order_by('date_added')
    for review in reviews:
        if review.book == current_book:
            pass
        else:
            reviews.remove(review)
    return reviews


@staff_member_required
def edit_book(request, pk):
    book = Book.objects.get(id=pk)
    
    if request.method == "GET":
        return render(request,'single_book.html',{'book':book,'edit':True})
    book.name = request.POST.get('name')
    book.authors = request.POST.get('author')
    book.year_published = request.POST.get('yearpublished')
    book.image = request.POST.get('image')
    book.save()
    messages.info(request,"Saved Successfuly")
    return redirect('books:mains')

##Author functions

def authors(request):
   all_authors = Authors.objects.all()
   context = {
       'authors_list': all_authors,
   }
   return render(request,'all_authors.html',context=context)

@staff_member_required
def add_author(request):
    if request.method == "POST":
        authorform = AuthorForm(request.POST, request.FILES)
        if authorform.is_valid():
            authorform.save()
            return redirect('books:authors')          
    else:
        authorform = AuthorForm()
   
    context = {
        'authorform': authorform,
    }
    return render(request, "add_author.html", context=context)
        

@staff_member_required
def delete_author(request,pk):
    author = Authors.objects.get(id=pk)
    author.delete()
    return redirect('books:authors')

def single_author(request, pk):
    author = Authors.objects.get(id=pk)
    return render(request,'single_author.html',{'author':author})

@staff_member_required
def edit_author(request, pk):
    author = Authors.objects.get(id=pk)
    if request.method == "GET":
        return render(request,'single_author.html',{'author':author,'edit':True})
    author.name = request.POST.get('name')
    author.age = request.POST.get('age')
    author.nationality = request.POST.get('nationality')
    author.save()
    messages.info(request,"Saved Successfuly")
    return redirect('books:authors')


def search_authors(request):
    search = request.GET.get('search')
    authors = Authors.objects.filter(Q(author__contains= search))
    context = {
        'authors_list' : authors,
    }
    return render(request, 'all_authors.html', context= context)






    

    





    

library/loans/views.py
from django.shortcuts import render,redirect
from books.models import Book
from loans.models import Loan
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from datetime import date, timedelta


@login_required
def loans(request, pk):
    current_book = Book.objects.get(id=pk)
    if current_book.status == "A":
        current_user = request.user
        loan = Loan(custID = current_user, bookID= current_book)
        loan.save()
        loantype = current_book.type
        loan.returndate = loan.loandate + timedelta(days=loantype)
        loan.save()
        current_book.status = "L"
        current_book.save()
        return redirect('books:mains')
    return redirect('books:mains')

@login_required
def returns(request, pk):
    current_loan = Loan.objects.get(id=pk)
    book = Book.objects.get(id=current_loan.bookID.id)
    book.status = "A"
    book.save()
    current_loan.delete()
    return redirect('loans:loans')

def late_check(pk):
    loan = Loan.objects.get(id = pk)
    current_date = date.today()
    if loan.returndate < current_date:
        loan.status = "O"
    else:
        loan.status = "V"
    loan.save()

@login_required
def loan_list_private(request):
    loans = Loan.objects.all()
    current_user = request.user
    loans_private = [{}]
    for loan in loans:
        late_check(loan.id)
        if loan.custID == current_user:
            loans_private.append(loan)

    context = {
        'loan_list': loans_private[1:],
    }
    return render(request, 'loans.html', context=context)
@staff_member_required
def loan_list(request):
    loans = Loan.objects.all()
    context = {
       'loan_list': loans,
    }
    return render(request,'tables.html',context=context)

@staff_member_required
def late_loans(request):
    loans = Loan.objects.all()
    late_loan = [{}]
    for loan in loans:
        late_check(loan.id)
        if loan.status == "O":
            late_loan.append(loan)
    context ={
        'loan_list': late_loan[1:],
    }
    return render(request, 'tables.html',context=context)

library/books/templates/add_author.html
{% extends "base.html" %}
{% block content %}
 
<center><form action="{% url 'books:add_author' %}" method="POST" enctype=multipart/form-data>
   {% csrf_token %}
   {{ authorform.as_p }}
   <input type="submit">
</form></center>
{% endblock %}

library/books/templates/add_book.html
{% extends "base.html" %}
{% block content %}
 
<center><form action="{% url 'books:addbook' %}" method="POST" enctype=multipart/form-data>
   {% csrf_token %}
   {{ bookform.as_p }}
   <input type="submit">
</form></center>
{% endblock %}

library/books/templates/all_authors.html
{%extends 'base.html' %}
{%block content%}
        <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">   
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for author in authors_list %}
        <div class="col mb-5">    
            <div class="card h-100">
                <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw">{{author.nationality}}</h5>
                        <h5 class="fw">{{author.age}}</h5>
                        <h1 class="fw-bolder">{{author.name}}</h1>
                    </div>
                </div>
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'books:single_author' author.id %}">Info</a></div>  
                </div>
            </div>
        </div>
        {%endfor%}    
    </section>
{%endblock%}
        

library/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>

    <body>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
      crossorigin="anonymous"></script>
      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container px-4 px-lg-5">
              <a class="navbar-brand" href="{% url 'books:mains' %}">Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                      {%if user.is_staff%}
                      <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'books:addbook' %}">Add Book</a></li>
                      {%endif%}
                      <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'books:loans' %}">My Loans</a></li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="#!">All Products</a></li>
                              <li><hr class="dropdown-divider" /></li>
                              <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                              <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                          </ul>
                      </li>
                  </ul>
                  <form class="d-flex" role="search" action=" {% url 'books:searchbooks' %} ">
                      <input name ="search" class="form-control me-3" type="search" placeholder="Enter author/book" aria-label="Search">
                      <button class="btn btn-outline-dark" type="submit">Search</button>
                  </form>
      
      {% if user.is_authenticated %}
      <span>Hello {{ user.username }}</span>
      <button type="button" class="btn btn-outline-dark" >
      <a href="{% url 'books:logout_func' %}">Log-Out</a>
      </button>
      {% else %}
      <button type="button" class="btn btn-outline-dark" >
        <a href="{% url 'books:login_func' %}">LogIn</a>
      </button>
      <button type="button" class="btn btn-outline-dark" >
          <a href="{% url 'books:register' %}">Register</a>
        </button>
      {% endif %}
          </div>
      </nav>
      <!-- Header-->
      <header class="bg-dark py-5">
          <div class="container px-4 px-lg-5 my-5">
              <div class="text-center text-white">
                  <h1 class="display-4 fw-bolder">Read in peace</h1>
                  <p class="lead fw-normal text-white-50 mb-0">With the new virtual Library</p>
              </div>
          </div>
      </header>
{%block content%}

{%endblock%}
<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Virtual Library 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

library/books/templates/loans.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% for loan in loan_list %}
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100 w-50">
        <img src="{% static 'images/' %}{{ loan.bookID.image }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">User {{ loan.custID }}</h5>
          {% if loan.status == "O" %}
          <p class="card-text"> <span class="badge text-bg-danger">{{ loan.get_status_display }}</span></p>
          {% else %}
          <p class="card-text"><span class="badge text-bg-success">{{ loan.get_status_display }}</span></p>
          {% endif %}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Book loaned {{ loan.bookID }}</li>
          <li class="list-group-item">Loan date {{ loan.loandate }}</li>
          <li class="list-group-item">Retrun date {{ loan.returndate }}</li>
        </ul>
        <div class="card-body">
          <a href="{% url 'books:return' loan.id %}" class="btn btn-success">Return book</a>
        </div>
      </div>
    </div>
 </div>
{% endfor %}
{% endblock %}

library/books/templates/mains.html
{%extends 'base.html' %}
{%block content%}
    <!-- Section-->
        <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">   
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for book in book_list %}
        <div class="col mb-5">    
            <div class="card h-100">
                <!-- Product image-->
                {% load static %}
                <img class="card-img-top" style="border: width 100px;height: 300px" src="{%static 'images/' %}{{ book.image }}" alt="..." /></img>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{book.name}}</h5>
                        <h5 class="fw-bolder">{{book.author}}</h5>
                        <h5 class="fw-bolder">{{book.year_published}}</h5>
                        <!-- Product reviews-->
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            Stars: {% if book.get_rating == 0 %}No ratings yet{% else %}{{ book.get_rating|floatformat:1 }}{% endif %}</h2>
                        </div>
                        <!-- Product price-->
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'books:single_book' book.id %}">Info</a></div>  
                </div>
                
            </div>
        </div>
        {%endfor%}    
    </section>
{%endblock%}
        

library/books/templates/single_author.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<script> function myFunction() {
    confirm("are you sure?");
}</script>
    {% if edit %}
    <center><form action="{% url 'books:edit_author' author.id %}" method="POST">
        {% csrf_token %}
        Author name:
        <input type="text" value="{{author.name}}" name="name"><br>
        Author age:
        <input type="text" value="{{author.age}}" name="age"><br>
        Nationality:
        <input type="text" value="{{author.nationallity}}" name="nationality"><br>
        <input type="submit" value="save edit">
    </form></center>
    {% else %}
    <center><div>
    Name:{{author.name}}<br>
    Age:{{author.age}}<br>
    nationality : {{author.nationality}}<br>
    <a href="{% url 'books:edit_author' author.id %}" class="btn btn-info">Edit author</a>
    <a href="{% url 'books:delete_author' author.id %}" onclick="return confirm('These author will be deleted forever, are you sure you want to delete this author?')" class="btn btn-danger">Delete author</a>
    {%endif%}
</div></center>
{% endblock %}

library/books/templates/single_book.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<script> function myFunction() {
    confirm("are you sure?");
}</script>
    {% if edit %}
    <center><form action="{% url 'books:edit' book.id %}" method="POST">
        {% csrf_token %}
        Book name:
        <input type="text" value="{{book.name}}" name="name"><br>
        Author:
        <input type="text" value="{{book.author}}" name="author"><br>
        Year published:
        <input type="date" value="{{book.year_published|date:'Y' }}" name="yearpublished"><br>
        Current image:<br>
        <img style="width:150px;height:200px" src="{% static 'images/' %}{{ book.image }}" class="card-img-top" alt="..." ><br>        
        Image:
        <input type="file" name="image" accept="image/*" id="id_image" required><br>
        <input type="submit" value="save edit">
    </form></center>
    {% else %}
    <center><div>
    <img style="width:150px;height:200px" src="{% static 'images/' %}{{ book.image }}" class="card-img-top" alt="..." >
    <hr/>
    Name:{{book.name}}<br>
    Author:{{book.author}}<br>
    Year published:{{book.year_published|date:"Y"}}<br>
    {% if user.is_staff%}
    <a href="{% url 'books:edit' book.id %}" class="btn btn-info">Edit book</a>
    <a href="{% url 'books:delbook' book.id %}" onclick="return confirm('The book will be deleted forever, are you sure you want to delete the book?')" class="btn btn-danger">Delete book</a>
    {%endif%}
    {% if book.status == "A" %}
    <a href="{% url 'loans:loan' book.id %}" class="btn btn-info">Loan book</a>
    {% else %}
    <button type="button" class="btn btn-info" disabled>On Loan</button>
    {% endif %}
    {% endif %}
    <hr>
        <h2 class="subtitle">Reviews</h2>
        <div class="reviews-wrapper">
            {% for review in reviews %}
                <div class="notification space-below">
                    <p>
                        <strong>Customer: </strong>{{ review.customer }},
                        <strong>Date: </strong>{{ review.date_added|date:"Y-m-d" }},
                        <strong>Stars: </strong>{{ review.stars }}
                    </p>
                    {{ review.content }}
                </div>
            {% empty %}
                <div class="notification space-below">
                    No reviews yet...
                </div>
            {% endfor %}
        </div>
        <div class="notification space-below">
            {% if request.user.is_authenticated %}
                <form method="post" action="{% url 'books:single_book' book.id %}">
                    {% csrf_token %}
                    <div class="field">
                        <label>Stars</label>
                        <div clas="control">
                            <div class="select">
                                <select name="stars">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3" selected>3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label>Content</label>
                        <div class="control">
                            <textarea class="textarea" name="content"></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Submit</button>
                        </div>
                    </div>
                </form>
            {% else %}
                <p>Please sign in to add review!</p>
            {% endif %}
        </div>
    </div>
</div></center>
{% endblock %}