library/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.mains,name= "mains"),
    path("mains/", views.mains,name= "mains"),
    path("addbook/",views.add_book,name="addbook"),
    path("<pk>/delbook", views.delete_book,name="delbook"),
    path('<pk>/singlebook', views.single_book, name="single_book"),
    path('<pk>/edit', views.edit_book, name="edit"),
    path('searchbooks', views.search_books, name="searchbooks"),
    path("authors/", views.authors,name= "authors"),
    path("addauthor/",views.add_author,name="add_author"),
    path("<pk>/delauthor", views.delete_author,name="delete_author"),
    path('<pk>/singleauthor', views.single_author, name="single_author"),
    path('<pk>/editauthor', views.edit_author, name="edit_author"),
    path('searchbooks', views.search_books, name="searchbooks")
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include('books.urls')),
    path("loans/", include('loans.urls')),
    path("users/", include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/loans/urls.py
from django.urls import path
from . import views

app_name = "loans"

urlpatterns = [ 
    path('<pk>/loan',views.loans,name= 'loan'),
    path('loans/',views.loan_list_private,name= 'loans'),
    path('adminloans/',views.loan_list,name= 'adminloans'),
    path('lateloans/',views.late_loans,name= 'lateloans'),
    path('<pk>/latecheck',views.late_check,name= 'latecheck'),
    path('<pk>/return',views.returns,name= 'return')
]

library/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_func, name="login_func"),
    path('loginout/', views.logout_func, name="logout_func"),
    path("register", views.register_request, name="register"),
    path('user/', views.user_menu, name="user"),
    path('showuser/', views.single_user, name="showuser"),
    path('firstlogin/', views.first_login, name="firstlogin"),
    path('customerlist/', views.customer_list, name="customerlist"),
    path('<pk>/deluser', views.deluser, name="deluser"),


]

library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Library - Django project</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
      </head>
        
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{% static 'css/styles_table.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts_table.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </head>

    <body>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
      crossorigin="anonymous"></script>
      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container px-4 px-lg-7">
              <a class="navbar-brand" href="{% url 'books:mains' %}">Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                      {%if user.is_staff%}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Actions</a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'books:addbook' %}">Add book</a></li>
                          <li><a class="dropdown-item" href="{% url 'loans:adminloans' %}">Loan List</a></li>
                          <li><a class="dropdown-item" href="{% url 'loans:lateloans' %}">Late Loans</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'users:customerlist' %}">Customers</a></li>
                          <li><a class="dropdown-item" href="{% url 'books:authors' %}">Authors List</a></li>
                          <li><a class="dropdown-item" href="{% url 'books:add_author' %}">Add Author</a></li>
                        </ul>
                      </li>
                      {%endif%}
                      <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'loans:loans' %}">My Loans</a></li>
                      {% if user.is_authenticated %}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"><img style="border-radius: 25px;" height="35px" width="35px" src="{% static 'images/' %}{{ user.userprofile.image }}"></a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" >{{user.username}}</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'users:showuser' %}">View profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'users:user' %}">Edit profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'users:logout_func' %}">Logout</a></li>
                        </ul>
                      </li>
                      {% else %}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Login</a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'users:login_func' %}">Login</a></li>
                          <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
                        </ul>
                      </li>
                      {% endif %}
                  </ul>
                  <form class="d-flex" role="search" action=" {% url 'books:searchbooks' %} ">
                      <input name ="search" class="form-control me-3" type="search" placeholder="Enter author/book" aria-label="Search">
                  </form>
          </div>
      </nav>
 
      <!-- Header-->
      <header class="bg-dark py-5">
          <div class="container px-4 px-lg-5 my-5">
              <div class="text-center text-white">
                  <h1 class="display-4 fw-bolder">Read in peace</h1>
                  <p class="lead fw-normal text-white-50 mb-0">With the new virtual Library</p>
              </div>
          </div>
      </header>
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %} 
{%block content%}

{%endblock%}
<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Virtual Library 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

library/templates/entry_form.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'books:login_func' %}" method='POST'>
    {% csrf_token %}
    <!-- Username input -->
    <div class="form-outline mb-4">
      <input type="text" id="form2Example1" class="form-control" name='username' />
      <label class="form-label" for="form2Example1">Username</label>
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
      <input type="password" id="form2Example2" class="form-control" name='password'/>
      <label class="form-label" for="form2Example2">Password</label>
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
          <label class="form-check-label" for="form2Example31"> Remember me </label>
        </div>
      </div>
  
      
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'books:register' %}">Register</a></p>
    </div>
  </form>

{% endblock %}

library/templates/register_form.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}   
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}      

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form action = {%url 'books:register'%} method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href='{% url 'books:login_func' %}'>login</a> instead.</p>
</div>
{% endblock content%}