library/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.mains,name= "mains"),
    path("mains/", views.mains,name= "mains"),
    path("addbook/",views.add_book,name="addbook"),
    path("<pk>/delbook", views.delete_book,name="delbook"),
    path('<pk>/singlebook', views.single_book, name="single_book"),
    path('<pk>/edit', views.edit_book, name="edit"),
    path('searchbooks', views.search_books, name="searchbooks"),
    path("authors/", views.authors,name= "authors"),
    path("addauthor/",views.add_author,name="add_author"),
    path("<pk>/delauthor", views.delete_author,name="delete_author"),
    path('<pk>/singleauthor', views.single_author, name="single_author"),
    path('<pk>/editauthor', views.edit_author, name="edit_author"),
    path('searchbooks', views.search_books, name="searchbooks")
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include('books.urls')),
    path("loans/", include('loans.urls')),
    path("users/", include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/loans/urls.py
from django.urls import path
from . import views

app_name = "loans"

urlpatterns = [ 
    path('<pk>/loan',views.loans,name= 'loan'),
    path('loans/',views.loan_list_private,name= 'loans'),
    path('adminloans/',views.loan_list,name= 'adminloans'),
    path('lateloans/',views.late_loans,name= 'lateloans'),
    path('<pk>/latecheck',views.late_check,name= 'latecheck'),
    path('<pk>/return',views.returns,name= 'return')
]

library/loans/models.py
from enum import Enum
from django.db import models
from django.contrib.auth.models import User
from books.models import Book

# Create your models here.


class LoanStatus(Enum):
   available = 1
   loaned = 2


class Loan(models.Model):
    class LoanTime(models.TextChoices):
       OVERTIME = 'O', 'Late Return'
       ONTIME = 'V' , 'Good'

    custID = models.ForeignKey(User, on_delete=models.CASCADE)
    bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
    loandate = models.DateField(auto_now_add=True)
    returndate = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=40, null=False, default= LoanTime.ONTIME, choices=LoanTime.choices)

    def __str__(self):
      return f'{self.custID} - {self.returndate}'

library/loans/views.py
from django.shortcuts import render,redirect
from books.models import Book
from loans.models import Loan
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from datetime import date, timedelta


@login_required
def loans(request, pk):
    current_book = Book.objects.get(id=pk)
    if current_book.status == "A":
        current_user = request.user
        loan = Loan(custID = current_user, bookID= current_book)
        loan.save()
        loantype = current_book.type
        loan.returndate = loan.loandate + timedelta(days=loantype)
        loan.save()
        current_book.status = "L"
        current_book.save()
        return redirect('books:mains')
    return redirect('books:mains')

@login_required
def returns(request, pk):
    current_loan = Loan.objects.get(id=pk)
    book = Book.objects.get(id=current_loan.bookID.id)
    book.status = "A"
    book.save()
    current_loan.delete()
    return redirect('loans:loans')

def late_check(pk):
    loan = Loan.objects.get(id = pk)
    current_date = date.today()
    if loan.returndate < current_date:
        loan.status = "O"
    else:
        loan.status = "V"
    loan.save()

@login_required
def loan_list_private(request):
    loans = Loan.objects.all()
    current_user = request.user
    loans_private = [{}]
    for loan in loans:
        late_check(loan.id)
        if loan.custID == current_user:
            loans_private.append(loan)

    context = {
        'loan_list': loans_private[1:],
    }
    return render(request, 'loans.html', context=context)
@staff_member_required
def loan_list(request):
    loans = Loan.objects.all()
    context = {
       'loan_list': loans,
    }
    return render(request,'tables.html',context=context)

@staff_member_required
def late_loans(request):
    loans = Loan.objects.all()
    late_loan = [{}]
    for loan in loans:
        late_check(loan.id)
        if loan.status == "O":
            late_loan.append(loan)
    context ={
        'loan_list': late_loan[1:],
    }
    return render(request, 'tables.html',context=context)

library/loans/templates/loans.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">   
  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
{% for loan in loan_list %}
<center><div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100 w-50">
        <img src="{% static 'images/' %}{{ loan.bookID.image }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">User {{ loan.custID }}</h5>
          {% if loan.status == "O" %}
          <p class="card-text"> <span class="badge text-bg-danger">{{ loan.get_status_display }}</span></p>
          {% else %}
          <p class="card-text"><span class="badge text-bg-success">{{ loan.get_status_display }}</span></p>
          {% endif %}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Book loaned {{ loan.bookID }}</li>
          <li class="list-group-item">Loan date {{ loan.loandate }}</li>
          <li class="list-group-item">Retrun date {{ loan.returndate }}</li>
        </ul>
        <div class="card-body">
          <a href="{% url 'loans:return' loan.id %}" class="btn btn-success">Return book</a>
        </div>
      </div>
    </div>
 </div></center>
{% endfor %}
  </div>
  </div>
</section>
{% endblock %}

library/loans/templates/tables.html
{%extends 'base.html'%}
{% load static%}
{%block content%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Library - admin tables</title>
    </head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                DataTable Example
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Book</th>
                            <th>Loan Date</th>
                            <th>Return Date</th>
                            <th>Loan status</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        {% for loan in loan_list %}
                        <tr>
                            <td>{{ loan.custID }}</td>
                            <td>{{ loan.bookID }}</td>
                            <td>{{ loan.loandate }}</td>
                            <td>{{ loan.returndate }}</td>
                            <td>{{ loan.get_status_display }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
            </div>
        </div>      
    </body>
</html>
{% endblock %}