library/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.mains,name= "mains"),
    path("mains/", views.mains,name= "mains"),
    path("addbook/",views.add_book,name="addbook"),
    path("<pk>/delbook", views.delete_book,name="delbook"),
    path('<pk>/singlebook', views.single_book, name="single_book"),
    path('<pk>/edit', views.edit_book, name="edit"),
    path('searchbooks', views.search_books, name="searchbooks"),
    path("authors/", views.authors,name= "authors"),
    path("addauthor/",views.add_author,name="add_author"),
    path("<pk>/delauthor", views.delete_author,name="delete_author"),
    path('<pk>/singleauthor', views.single_author, name="single_author"),
    path('<pk>/editauthor', views.edit_author, name="edit_author"),
    path('searchbooks', views.search_books, name="searchbooks")
]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include('books.urls')),
    path("loans/", include('loans.urls')),
    path("users/", include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_func, name="login_func"),
    path('loginout/', views.logout_func, name="logout_func"),
    path("register", views.register_request, name="register"),
    path('user/', views.user_menu, name="user"),
    path('showuser/', views.single_user, name="showuser"),
    path('firstlogin/', views.first_login, name="firstlogin"),
    path('customerlist/', views.customer_list, name="customerlist"),
    path('<pk>/deluser', views.deluser, name="deluser"),


]

library/users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=30, null=True, default='Joe Joe')
    image = models.ImageField(null=True, blank=True, default='userholder.png')
    city = models.CharField(max_length=20, null=True, default='Tel Aviv')
    age = models.SmallIntegerField(null=True, default=12)

    def __str__(self):
        return f'{self.fullname}, {self.city}'

library/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

		

library/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import NewUserForm
from users.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required


def login_func(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            User.objects.get(username=username)
        except:
            messages.error(request, 'USER NOT EXISTS')
            return render(request, 'entry_form.html', {}) 
        
        user = authenticate(username = username,password = password)
        if user is not None:
            login(request,user)
            return redirect('books:mains')
        else:
            messages.error(request, 'PASSWORD ERROR OCCURRED WHILE LOG-IN') 

    return render(request, 'entry_form.html', {})


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("users:firstlogin")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()

	return render(request, "register_form.html", context={"register_form":form})

def logout_func(request):
    logout(request)

    return redirect('books:mains')

@login_required
def single_user(request):
    user = UserProfile.objects.get(user=request.user)

    return render(request,'user.html',{'user':user})

@login_required
def user_menu(request):
    try:
        profile = UserProfile(user=request.user)
        profile.save()
    except:
        user = UserProfile.objects.get(user=request.user)
    if request.method == "GET":
        return render(request,'user.html',{'user':user,'edit':True})
    user.fullname = request.POST.get('fullname')
    user.city = request.POST.get('city')
    user.age = request.POST.get('age')
    user.image = request.POST.get('image')
    user.save()
    messages.info(request,"Saved Successfuly")

    return redirect('users:showuser')

def first_login(request):
     profile = UserProfile(user=request.user)
     profile.save()
     return redirect('books:mains')

@staff_member_required
def customer_list(request):
    users = UserProfile.objects.all()
    return render(request,'all_users.html',{'users':users})

@staff_member_required
def deluser(request, pk):
    user = User.objects.get(id=pk)
    user.delete()
    return redirect('users:customerlist')

    

library/users/templates/add_profile.html
{% extends "base.html" %}
{% block content %}
 
<form action="{% url 'users:addprofile' %}" method="POST" enctype=multipart/form-data>
   {% csrf_token %}
   {{ userform.as_p }}
   <input type="submit">
</form>
{% endblock %}

library/users/templates/all_users.html
{%extends 'base.html' %}
{%block content%}
        <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">   
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for user in users %}
        <div class="col mb-5">    
            <div class="card h-100">
                {% load static %}
                <img class="card-img-top" src="{%static 'images/' %}{{ user.image }}" alt="{% static 'images/userholder' %}" /></img>
                <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw">{{user.user.username}}</h5>
                        <h5 class="fw">{{user.age}}</h5>
                        <h1 class="fw-bolder">{{user.city}}</h1>
                        <h5 class="fw">{{user.fullname}}</h5>
                    </div>
                </div>
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <a href="{% url 'users:deluser' user.user.id %}" onclick="return confirm('The customer will be deleted forever, are you sure you want to delete the customer?')" class="btn btn-danger">Delete customer</a>                </div>
                
            </div>
        </div>
        {%endfor%}    
    </section>
{%endblock%}
        

library/users/templates/entry_form.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}

{% endif %}

<center><form action="{% url 'users:login_func' %}" method='POST'>
    {% csrf_token %}
    <!-- Username input -->
    <div class="row g-3">
      <div class="form-outline mb-4">
      <div class="col-sm-10">
        Username:<br>
        <input type="text" class="form-control" name='username' aria-label="Username">
      </div>
    </div>
    <!-- Password input -->
    <div class="form-outline mb-4">
    <div class="col-sm-10">
      Password:<br>
      <input type="password" class="form-control" name='password' aria-label="Password">
    </div>
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <!-- Checkbox -->
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
          <label class="form-check-label" for="form2Example31"> Remember me </label>
        </div>
      </div>
  
      
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary  col-auto">Sign in</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'users:register' %}">Register</a></p>
    </div>
  </form></center>

{% endblock %}

library/users/templates/register_form.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}   
     

<!--Register--> 
<center><div class="container py-5"><left>
	<h1>Register</h1>
	<form action = "{% url 'users:register' %}" method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'users:login_func' %}">login</a> instead.</p>
</left></div></center>
{% endblock content%}

library/users/templates/user.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if edit %}

    <center><form action="{% url 'users:user' %}" method="POST">
        {% csrf_token %}
        Fullname:
        <input type="text" value="{{ user.fullname }}" name="fullname"><br>
        City:
        <input type="text" value="{{ user.city }}" name="city"><br>
        Age:
        <input type="number" value="{{ user.age }}" name="age"><br>
        Current image:<br>
        <img style="width:50px;height:50px" src="{% static 'images/' %}{{ user.image }}" class="card-img-top" alt="..." ><br>        
        Image:
        <input type="file" name="image" accept="image/*" id="id_image" required><br>
        <input type="submit" value="save edit">
    </form></center>
    
    {% else %}
   <center> <div>
    <img style="width:150px;height:200px" src="{% static 'images/' %}{{ user.image }}" class="card-img-top" alt="..." >
    <hr/>
    Name:{{user.fullname}}<br>
    City:{{user.city}}<br>
    Age:{{user.age}}<br>
    <a href="{% url 'users:user' %}" class="btn btn-info">Edit user</a>
</div></center>
    {% endif %}
   
    

{% endblock %}